export default {
  "0058b4c6": [() => import(/* webpackChunkName: "0058b4c6" */ "@generated/docusaurus-plugin-content-docs/default/p/docs-175.json"), "@generated/docusaurus-plugin-content-docs/default/p/docs-175.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/docs-175.json")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1cf99db0": [() => import(/* webpackChunkName: "1cf99db0" */ "@site/docs/modules/ros2-nervous-system.md"), "@site/docs/modules/ros2-nervous-system.md", require.resolveWeak("@site/docs/modules/ros2-nervous-system.md")],
  "361507c1": [() => import(/* webpackChunkName: "361507c1" */ "@site/src/pages/chatbot/index.js"), "@site/src/pages/chatbot/index.js", require.resolveWeak("@site/src/pages/chatbot/index.js")],
  "54f44165": [() => import(/* webpackChunkName: "54f44165" */ "@site/docs/getting-started/installation.md"), "@site/docs/getting-started/installation.md", require.resolveWeak("@site/docs/getting-started/installation.md")],
  "588bd741": [() => import(/* webpackChunkName: "588bd741" */ "@site/docs/getting-started/quick-start.md"), "@site/docs/getting-started/quick-start.md", require.resolveWeak("@site/docs/getting-started/quick-start.md")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "7d744e69": [() => import(/* webpackChunkName: "7d744e69" */ "@site/docs/intro/intro.md"), "@site/docs/intro/intro.md", require.resolveWeak("@site/docs/intro/intro.md")],
  "94c0fd3a": [() => import(/* webpackChunkName: "94c0fd3a" */ "@site/docs/modules/vla-module.md"), "@site/docs/modules/vla-module.md", require.resolveWeak("@site/docs/modules/vla-module.md")],
  "98cd2349": [() => import(/* webpackChunkName: "98cd2349" */ "@site/docs/modules/ai-robot-brain.md"), "@site/docs/modules/ai-robot-brain.md", require.resolveWeak("@site/docs/modules/ai-robot-brain.md")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "c4f5d8e4": [() => import(/* webpackChunkName: "c4f5d8e4" */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  "ece68872": [() => import(/* webpackChunkName: "ece68872" */ "@site/docs/modules/digital-twin.md"), "@site/docs/modules/digital-twin.md", require.resolveWeak("@site/docs/modules/digital-twin.md")],};
